# Generated by Django 5.2 on 2025-05-28 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookAdAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_account_id', models.CharField(max_length=100, unique=True)),
                ('ad_account_name', models.CharField(blank=True, max_length=255)),
                ('access_token', models.TextField()),
                ('app_id', models.CharField(max_length=100)),
                ('app_secret', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facebook_ad_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facebook Ad Account',
                'verbose_name_plural': 'Facebook Ad Accounts',
            },
        ),
        migrations.CreateModel(
            name='FacebookAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.CharField(max_length=100, unique=True)),
                ('ad_name', models.CharField(max_length=255)),
                ('campaign_id', models.CharField(max_length=100)),
                ('campaign_name', models.CharField(max_length=255)),
                ('adset_id', models.CharField(max_length=100)),
                ('adset_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('DELETED', 'Deleted'), ('PENDING_REVIEW', 'Pending Review'), ('DISAPPROVED', 'Disapproved'), ('PREAPPROVED', 'Preapproved'), ('PENDING_BILLING_INFO', 'Pending Billing Info'), ('CAMPAIGN_PAUSED', 'Campaign Paused'), ('ARCHIVED', 'Archived')], max_length=50)),
                ('objective', models.CharField(blank=True, max_length=100)),
                ('impressions', models.BigIntegerField(default=0)),
                ('clicks', models.BigIntegerField(default=0)),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ctr', models.FloatField(default=0)),
                ('cpm', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cpc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_time', models.DateTimeField(blank=True, null=True)),
                ('updated_time', models.DateTimeField(blank=True, null=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('ad_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='facebook_ads.facebookadaccount')),
            ],
            options={
                'verbose_name': 'Facebook Ad',
                'verbose_name_plural': 'Facebook Ads',
                'ordering': ['-last_synced'],
            },
        ),
    ]
