# Generated by Django 5.2 on 2025-06-02 16:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_ads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facebookadaccount',
            options={},
        ),
        migrations.AddField(
            model_name='facebookad',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facebookad',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='facebookad',
            name='adset_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='facebookad',
            name='adset_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='facebookad',
            name='campaign_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='facebookad',
            name='campaign_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='facebookad',
            name='spend',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='facebookad',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='facebookadaccount',
            name='ad_account_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='facebookadaccount',
            name='app_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='facebookadaccount',
            unique_together={('user', 'ad_account_id')},
        ),
        migrations.CreateModel(
            name='FacebookCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign_id', models.CharField(max_length=100, unique=True)),
                ('campaign_name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('effective_status', models.CharField(blank=True, max_length=50)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('ad_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='facebook_ads.facebookadaccount')),
            ],
            options={
                'unique_together': {('ad_account', 'campaign_id')},
            },
        ),
        migrations.CreateModel(
            name='SelectedCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_monitoring', models.BooleanField(default=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='facebook_ads.facebookcampaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'campaign')},
            },
        ),
    ]
