# Generated by Django 5.2.3 on 2025-06-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_ads', '0003_remove_unique_together_constraint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookad',
            name='objective',
        ),
        migrations.AddField(
            model_name='facebookad',
            name='actions_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='facebookad',
            name='bid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='facebookad',
            name='billing_event',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facebookad',
            name='call_to_action_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facebookad',
            name='campaign_objective',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facebookad',
            name='configured_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='facebookad',
            name='conversion_rate_ranking',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='facebookad',
            name='conversion_specs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='facebookad',
            name='conversions_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='facebookad',
            name='creative_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='facebookad',
            name='creative_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facebookad',
            name='creative_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='facebookad',
            name='creative_title',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='facebookad',
            name='creative_video_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facebookad',
            name='effective_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='facebookad',
            name='engagement_rate_ranking',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='facebookad',
            name='frequency',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='facebookad',
            name='inline_link_clicks',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facebookad',
            name='link_url_clicks',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facebookad',
            name='optimization_goal',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facebookad',
            name='outbound_clicks',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facebookad',
            name='promoted_object',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='facebookad',
            name='purchase_roas',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='facebookad',
            name='quality_ranking',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='facebookad',
            name='reach',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facebookad',
            name='targeting_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='facebookad',
            name='tracking_specs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='facebookad',
            name='unique_clicks',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facebookad',
            name='unique_ctr',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='facebookad',
            name='video_avg_time_watched',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='facebookad',
            name='video_p100_watched',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facebookad',
            name='video_p25_watched',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facebookad',
            name='video_p50_watched',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facebookad',
            name='video_p75_watched',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facebookad',
            name='website_purchase_roas',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='facebookcampaign',
            name='actions_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='facebookcampaign',
            name='bid_strategy',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facebookcampaign',
            name='budget_remaining',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='facebookcampaign',
            name='buying_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facebookcampaign',
            name='clicks',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facebookcampaign',
            name='conversions_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='facebookcampaign',
            name='cpc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='facebookcampaign',
            name='cpm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='facebookcampaign',
            name='created_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facebookcampaign',
            name='ctr',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='facebookcampaign',
            name='daily_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='facebookcampaign',
            name='frequency',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='facebookcampaign',
            name='impressions',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facebookcampaign',
            name='inline_link_clicks',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facebookcampaign',
            name='lifetime_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='facebookcampaign',
            name='link_url_clicks',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facebookcampaign',
            name='objective',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facebookcampaign',
            name='outbound_clicks',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facebookcampaign',
            name='purchase_roas',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='facebookcampaign',
            name='reach',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facebookcampaign',
            name='special_ad_categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='facebookcampaign',
            name='spend',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='facebookcampaign',
            name='spend_cap',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='facebookcampaign',
            name='stop_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facebookcampaign',
            name='updated_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facebookcampaign',
            name='website_purchase_roas',
            field=models.FloatField(default=0),
        ),
    ]
