# Generated by Django 5.2 on 2025-10-15 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_ads', '0005_dashboardperiod_facebookadset_facebookadinsights_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(unique=True)),
            ],
            options={
                'verbose_name': 'Daily Period',
                'verbose_name_plural': 'Daily Periods',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='OptimizationStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rules', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimization_strategies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Optimization Strategy',
                'verbose_name_plural': 'Optimization Strategies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignOptimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_enabled', models.DateTimeField(auto_now_add=True)),
                ('date_disabled', models.DateTimeField(blank=True, null=True)),
                ('optimization_start_date', models.DateField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimizations', to='facebook_ads.facebookcampaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_optimizations', to=settings.AUTH_USER_MODEL)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_links', to='facebook_ads.optimizationstrategy')),
            ],
            options={
                'verbose_name': 'Campaign Optimization',
                'verbose_name_plural': 'Campaign Optimizations',
                'ordering': ['-date_enabled'],
                'unique_together': {('campaign', 'strategy')},
            },
        ),
        migrations.CreateModel(
            name='OptimizationMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cpc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cpm', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ctr', models.FloatField(default=0)),
                ('impressions', models.BigIntegerField(default=0)),
                ('clicks', models.BigIntegerField(default=0)),
                ('add_to_carts', models.IntegerField(default=0)),
                ('purchases', models.IntegerField(default=0)),
                ('purchase_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('roas', models.FloatField(default=0)),
                ('campaign_status', models.CharField(blank=True, max_length=50)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimization_metrics', to='facebook_ads.facebookcampaign')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_metrics', to='facebook_ads.dailyperiod')),
            ],
            options={
                'verbose_name': 'Optimization Metrics',
                'verbose_name_plural': 'Optimization Metrics',
                'ordering': ['-period__date'],
                'indexes': [models.Index(fields=['campaign', 'period'], name='facebook_ad_campaig_05e52d_idx'), models.Index(fields=['period'], name='facebook_ad_period__a0840e_idx')],
                'unique_together': {('campaign', 'period')},
            },
        ),
        migrations.CreateModel(
            name='OptimizationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_time', models.DateTimeField(auto_now_add=True)),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cpc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ctr', models.FloatField(default=0)),
                ('impressions', models.BigIntegerField(default=0)),
                ('clicks', models.BigIntegerField(default=0)),
                ('add_to_carts', models.IntegerField(default=0)),
                ('purchases', models.IntegerField(default=0)),
                ('roas', models.FloatField(default=0)),
                ('action', models.CharField(choices=[('KEEP_RUNNING', 'Keep Running'), ('PAUSE', 'Pause Campaign'), ('SCALE_UP', 'Scale Up Budget'), ('SCALE_DOWN', 'Scale Down Budget'), ('NO_ACTION', 'No Action Needed')], max_length=20)),
                ('rule_triggered', models.CharField(blank=True, max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('action_successful', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimization_logs', to='facebook_ads.facebookcampaign')),
                ('campaign_optimization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='facebook_ads.campaignoptimization')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='facebook_ads.optimizationstrategy')),
            ],
            options={
                'verbose_name': 'Optimization Log',
                'verbose_name_plural': 'Optimization Logs',
                'ordering': ['-check_time'],
                'indexes': [models.Index(fields=['campaign', 'check_time'], name='facebook_ad_campaig_78ae02_idx'), models.Index(fields=['strategy', 'check_time'], name='facebook_ad_strateg_359a08_idx'), models.Index(fields=['check_time'], name='facebook_ad_check_t_26f87a_idx')],
            },
        ),
    ]
