# Generated by Django 5.2 on 2025-09-23 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('app_id', models.CharField(max_length=100, unique=True)),
                ('app_secret', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('environment', models.CharField(choices=[('development', 'Development'), ('production', 'Production')], default='development', max_length=20)),
                ('webhook_url', models.URLField(blank=True)),
                ('webhook_verify_token', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Facebook App',
                'verbose_name_plural': 'Facebook Apps',
            },
        ),
        migrations.CreateModel(
            name='FacebookToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_token', models.TextField(help_text='Facebook access token')),
                ('token_type', models.CharField(default='user_access_token', max_length=50)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.JSONField(default=list, help_text='Granted permissions/scopes')),
                ('facebook_user_id', models.CharField(max_length=100, unique=True)),
                ('facebook_user_name', models.CharField(blank=True, max_length=255)),
                ('facebook_user_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facebook_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facebook Token',
                'verbose_name_plural': 'Facebook Tokens',
            },
        ),
    ]
